### PR TITLE
provided compiled SpiLight

### PR DESCRIPTION
**Pull request by swharden**
I compiled the SpiLight project without modification

### CODE REVIEW

**Comment by zhelnio** [comment]
Added. Thanks!

**Comment by cmorty** [comment]
IMHO this was a bad idea. One should not put compiled files into version control. It's much better to use [Appveyor](https://www.appveyor.com) (free for OSS) to create binaries and upload them to [nuget.org](https://www.nuget.org/).  - Google provides some instructions.

**Comment by swharden** [comment]
@cmorty I do agree, as adding EXE files to a GitHub respiratory feels odd. My intent was to make the EXE downloadable with a single click. When I found this project I just wanted to test if the program worked with my FTDI hardware before diving into the code. As it was, the only way to do this was to require the end user to _download and install visual studio_!

Appveyor and nuget seem like an option, but may be more complex than required. Keep in mind my only suggestion was to have a link to be able to download the EXE. Is there a "pastebin" or "photobucket" for EXE files?

Looking forward to your thoughts!

**Comment by cmorty** [comment]
@swharden  Oh that's what github provides releases for. It is already used by MPSSELight: https://github.com/zhelnio/MPSSELight/releases Updating the readme might be a better Idea.

**Comment by zhelnio** [comment]
Dear @cmorty ! This project is still interesting for me, but it is sometimes hard to provide its quality real time support nowadays. What if I'll add you to the Collaborators list to give the direct write access to the repository? What do you think about it?

**Comment by cmorty** [comment]
@zhelnio I totally understand you. I also have similar projects: Eventually one moves on to other projects. Yes I'm fine with that, at least for the next 6 Month or so - maybe longer. Depends on the project. ;)

**Pull request merged**
